### ISSUE TITLE
Hierarchal Inheritance

### ISSUE THREAD

**Issue by NotoriousENG** [TheNitesWhoSay/RareCpp#73]
Hello,

I am unable to find any documentation or usage for Hierarchical Inheritance. This is my use case (May have some minor typos).

```
Note(Object)
class Object
{
public: 
    float f1;
    REFLECT(Object, f1)
}

Note(DerivedObject, Super<Object>)
class DerivedObject : public Object
{
public:
    float f2;
    REFLECT_NOTED(DerivedDerivedObject, f2)
}

Note(DerivedDerivedObject, Super<DerivedObject>)
class DerivedDerivedObject : public DerivedObject
{
public:
    float f3;

    void PrintInfo()
    {
        DerivedDerivedObject::Supers::ForEach(*this, [&](auto superInfo, auto& superObj) { 
    	    using Super = typename decltype(superInfo)::Type; 
    	    Super::Class::ForEachField(superObj, [&](auto& field, auto& value) { 
    		    std::cout << "  " << field.name << ": " << value << std::endl; 
    		}); 
	    }); 
        DerivedDerivedObject::Class::ForEachField(*this, [&](auto& field, auto& value) 
        	{ 
        		std::cout << "  " << field.name << ": " << value << std::endl; 
        	});
    }
    REFLECT_NOTED(DerivedDerivedObject, f3)
}
```

Expected Output:
```
 f1: 1
 f2: 2
 f3: 3 
```

Actual Output:
```
 f2: 2
 f3: 3
```

Currently, I can get my desired behavior via
`Note(DerivedDerivedObject, Super<Object>, Super<DerivedObject>)`

But I see this becoming hard to manage in the future, is there any way to access Supers recursively?

It is my understanding that Supers::ForEach calls Supers::ForEachRecursion(...) so I am unsure why this does not access the underlying Object.

Thank you for your support! RareCpp has been a joy to use so far!

**Comment by TheNitesWhoSay** [comment]
Good Evening,

Supers::ForEach refers to all of the super classes for the current type (e.g. class B : A {}; class D : public B, public C {}; Supers::ForEach on D gets you B and C, but not A), if you want to traverse up further you could call Supers::ForEach on DerivedObject (or "Super" as you've aliased it); but my real recommendation is that you recurse your print function; or even better (if you don't need different print logic for each class): externalize your printer so you can use it on any class.

I've placed examples of these approaches here: https://godbolt.org/z/T8dn5Mr5K (starting from your provided code, fixing some casing and missing semi colons, and you also reflected "DerivedDerivedObject" when your intent seems to be "DerivedObject")

Hope this helps!

**Comment by NotoriousENG** [comment]
Your generic approach was exactly what I was looking for.

Thank you!
