### ISSUE TITLE
How to check whether there exists a field of specific type?

### ISSUE THREAD

**Issue by hooyuser** [TheNitesWhoSay/RareCpp#94]
Given a specific type, say `int`, how to check whether there exists an integer field at compile time?

Or are there some ways to get a tuple of field types? So I can check types like this.
```
struct Pos {
	float x;
	int y;
	using MemberTypes = std::tuple<float, int>;
};

constexpr bool has_int_member = [] <typename... Ts> (std::tuple<Ts...>) {
       return (std::is_same_v<Ts, int> | ...);
}(Pos::MemberTypes{});

static_assert(has_int_member);
```

**Comment by TheNitesWhoSay** [comment]
Support for fold expressions coming soon! In the meantime, this trait works for your use case: https://godbolt.org/z/dab4o8nMK

**Comment by hooyuser** [comment]
Thank you for your quick reply. That works for me. Expect to see how folding expressions will work in the future!
